CREATE TABLE savings_challenges (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    target_amount NUMBER,
    start_date DATE,
    end_date DATE,
    total_saved NUMBER DEFAULT 0
);

CREATE TABLE challenge_days (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_id NUMBER,
    day_date DATE,
    amount NUMBER,
    completed NUMBER DEFAULT 0
);
COMMIT;
